dist: trusty
language: generic
matrix:
  include:
    - language: c++
      compiler: gcc
    - addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - g++-8
      env: CC=gcc-8 CXX=g++-8

os:
- linux

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - systemtap-sdt-dev
      - libelf-dev

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake ..
  - cmake --build build
