name: CUBRID Code Style
on: [pull_request, push]

###############
# Set the Job #
###############
jobs:
  code-style:

    runs-on: [ubuntu-latest]

    ##################
    # Load all steps #
    ##################
    steps:
      #################
      # Install tools #
      #################
      - name: Install GNU indent and Astyle
        run: sudo apt-get install -y indent astyle
      - name: Install Git
        run: sudo apt-get install -y git
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Head
        uses: actions/checkout@v2
      #################################
      # Listing files from the change #
      #################################
      - name: List files for pull_request
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const PULL_REQUEST_FILES = github.pulls.listFiles({
              context.repo.owner,
              context.repo.repo,
              context.issue.number
            });

            console.log(PULL_REQUEST_FILES)

            var re = /(?:\.([^.]+))?$/;
            var C_FILES = [];
            var CPP_FILES = [];
            for (const f of PULL_REQUEST_FILES) {
              var name = PULL_REQUEST_FILES.file_name;
              var extension = re.exec (name);

              switch (extension) {
                case 'c':
                case 'h':
                case 'i':
                  C_FILES.push(name);
                  break;
                case 'cpp':
                case 'hpp':
                case 'ipp':
                  CPP_FILES.push(name);
                  break;
              }
            }

            console.log(C_FILES);
            console.log(CPP_FILES);